module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascadel',
    'Tumbling',
    'Silent T',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    ' Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.Places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'Riverl',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
]